command /bossspawn:
  permission: operator
  trigger:
    broadcast "&cBoss has been summoned by &f%player%&c!"
    spawn 1 zombie at location of player
    equip last spawned zombie with diamond helmet of protection 10
    equip last spawned zombie with diamond chestplate of protection 10
    equip last spawned zombie with diamond leggings of protection 10
    equip last spawned zombie with diamond boots of protection 10
